// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MindMapManager.Infrastructure.DatabaseContext;

#nullable disable

namespace MindMapManager.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bookmark", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("ResId")
                        .HasColumnType("int")
                        .HasColumnName("res_id");

                    b.HasKey("UserId", "ResId")
                        .HasName("pk_bookmark");

                    b.HasIndex(new[] { "ResId" }, "idx_bookmark_res_id");

                    b.HasIndex(new[] { "UserId" }, "idx_bookmark_user_id");

                    b.ToTable("bookmark", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Member",
                            NormalizedName = "MEMBER"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsVerified")
                        .HasColumnType("bit")
                        .HasColumnName("is_verified");

                    b.Property<DateTime?>("LastActDate")
                        .HasColumnType("datetime")
                        .HasColumnName("last_act_date");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OtpCode")
                        .HasColumnType("int")
                        .HasColumnName("otp_code");

                    b.Property<DateTime?>("OtpExpire")
                        .HasColumnType("datetime")
                        .HasColumnName("otp_expire");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("Pid")
                        .HasColumnType("int")
                        .HasColumnName("pid");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<int?>("Streak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("streak");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Pid");

                    b.HasIndex(new[] { "LastActDate" }, "idx_user_last_act_date");

                    b.HasIndex(new[] { "Status" }, "idx_user_status");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.Certificate", b =>
                {
                    b.Property<int>("CertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cert_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CertId"));

                    b.Property<string>("CertUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("cert_url");

                    b.Property<string>("CertificateCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar()");

                    b.Property<DateTime?>("IssuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("issued_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("Rid")
                        .HasColumnType("int")
                        .HasColumnName("rid");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("CertId")
                        .HasName("PK__certific__024B46EC706205C1");

                    b.HasIndex(new[] { "CertUrl" }, "UQ__certific__98B88B7F87AEF197")
                        .IsUnique()
                        .HasFilter("[cert_url] IS NOT NULL");

                    b.HasIndex(new[] { "Rid" }, "idx_certificate_rid");

                    b.HasIndex(new[] { "UserId" }, "idx_certificate_user_id");

                    b.ToTable("certificate", (string)null);
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.Comment", b =>
                {
                    b.Property<int>("ComId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("com_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("ParentComId")
                        .HasColumnType("int")
                        .HasColumnName("parent_com_id");

                    b.Property<int?>("TopicId")
                        .HasColumnType("int")
                        .HasColumnName("topic_id");

                    b.HasKey("ComId")
                        .HasName("PK__comment__5066738CC2CD55D0");

                    b.HasIndex(new[] { "ParentComId" }, "idx_comment_parent_com_id");

                    b.HasIndex(new[] { "TopicId" }, "idx_comment_topic_id");

                    b.ToTable("comment", (string)null);
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.CompletedTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("topicId")
                        .HasColumnType("int")
                        .HasColumnName("topic_id");

                    b.Property<int>("userId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("topicId");

                    b.HasIndex("userId");

                    b.ToTable("completed_topics", (string)null);
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.Level", b =>
                {
                    b.Property<int>("Lid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("lid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Lid"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int?>("Rid")
                        .HasColumnType("int")
                        .HasColumnName("rid");

                    b.HasKey("Lid")
                        .HasName("PK__level__DE105D0723A1DED8");

                    b.HasIndex(new[] { "Rid" }, "idx_level_rid");

                    b.ToTable("level", (string)null);
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.Notification", b =>
                {
                    b.Property<int>("NotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("not_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("message");

                    b.Property<bool>("Read")
                        .HasColumnType("bit")
                        .HasColumnName("read");

                    b.Property<int?>("RefId")
                        .HasColumnType("int")
                        .HasColumnName("ref_id");

                    b.Property<string>("RefType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ref_type");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("NotId")
                        .HasName("PK__notifica__0E4BE3002DCFD2AB");

                    b.HasIndex(new[] { "Read" }, "idx_notification_read");

                    b.HasIndex(new[] { "UserId" }, "idx_notification_user_id");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.Plan", b =>
                {
                    b.Property<int>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Pid"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price");

                    b.HasKey("Pid")
                        .HasName("PK__plan__DD37D91A1E7995DF");

                    b.ToTable("plan", (string)null);
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.Progress", b =>
                {
                    b.Property<int>("ProgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("prog_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgId"));

                    b.Property<decimal>("CompPerc")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("comp_perc");

                    b.Property<int?>("Lid")
                        .HasColumnType("int")
                        .HasColumnName("lid");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ProgId")
                        .HasName("PK__progress__8C41E25C33043CD1");

                    b.HasIndex(new[] { "Lid" }, "idx_progress_lid");

                    b.HasIndex(new[] { "UserId" }, "idx_progress_user_id");

                    b.HasIndex(new[] { "UserId", "Lid" }, "user_progress_level_uq")
                        .IsUnique()
                        .HasFilter("[user_id] IS NOT NULL AND [lid] IS NOT NULL");

                    b.ToTable("progress", (string)null);
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.Project", b =>
                {
                    b.Property<int>("ProjId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("proj_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<int?>("Lid")
                        .HasColumnType("int")
                        .HasColumnName("lid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("ProjId")
                        .HasName("PK__project__A04A0C2D8FB345F5");

                    b.HasIndex(new[] { "Lid" }, "idx_project_lid");

                    b.ToTable("project", (string)null);
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.Resource", b =>
                {
                    b.Property<int>("ResId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("res_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("order");

                    b.Property<bool?>("Paid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("paid");

                    b.Property<string>("ResUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("res_url");

                    b.Property<int?>("TopicId")
                        .HasColumnType("int")
                        .HasColumnName("topic_id");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("type");

                    b.HasKey("ResId")
                        .HasName("PK__resource__2090B50D06C7CAAD");

                    b.HasIndex(new[] { "Paid" }, "idx_resource_paid");

                    b.HasIndex(new[] { "TopicId" }, "idx_resource_topic_id");

                    b.HasIndex(new[] { "Type" }, "idx_resource_type");

                    b.ToTable("resource", (string)null);
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.Review", b =>
                {
                    b.Property<int>("RevId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rev_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RevId"));

                    b.Property<string>("Content")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("Rate")
                        .HasColumnType("int")
                        .HasColumnName("rate");

                    b.Property<int?>("Rid")
                        .HasColumnType("int")
                        .HasColumnName("rid");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("RevId")
                        .HasName("PK__review__397465D6E4969990");

                    b.HasIndex(new[] { "Rid" }, "idx_review_rid");

                    b.HasIndex(new[] { "UserId" }, "idx_review_user_id");

                    b.HasIndex(new[] { "UserId", "Rid" }, "user_review_roadmap_uq")
                        .IsUnique()
                        .HasFilter("[user_id] IS NOT NULL AND [rid] IS NOT NULL");

                    b.ToTable("review", (string)null);
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.Roadmap", b =>
                {
                    b.Property<int>("Rid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Rid"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int?>("TrackId")
                        .HasColumnType("int")
                        .HasColumnName("track_id");

                    b.HasKey("Rid")
                        .HasName("PK__roadmap__C2B7EDE8844A8F08");

                    b.HasIndex(new[] { "TrackId" }, "idx_roadmap_track_id");

                    b.ToTable("roadmap", (string)null);
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.Topic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("topic_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TopicId"));

                    b.Property<int?>("Lid")
                        .HasColumnType("int")
                        .HasColumnName("lid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("order");

                    b.HasKey("TopicId")
                        .HasName("PK__topic__D5DAA3E97151A72F");

                    b.HasIndex(new[] { "Lid" }, "idx_topic_lid");

                    b.ToTable("topic", (string)null);
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.Track", b =>
                {
                    b.Property<int>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("track_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrackId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("icon_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("TrackId")
                        .HasName("PK__track__24ECC82ED7FB6338");

                    b.ToTable("track", (string)null);
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.UserComment", b =>
                {
                    b.Property<int>("ComId")
                        .HasColumnType("int")
                        .HasColumnName("com_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ComId")
                        .HasName("PK__user_com__5066738C8EC67004");

                    b.HasIndex(new[] { "ComId" }, "idx_user_comment_com_id");

                    b.HasIndex(new[] { "UserId" }, "idx_user_comment_user_id");

                    b.ToTable("user_comment", (string)null);
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.UserProject", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("ProjId")
                        .HasColumnType("int")
                        .HasColumnName("proj_id");

                    b.Property<DateTime?>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("submitted_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("UserId", "ProjId")
                        .HasName("PK__user_pro__73BA97CD94F2D5C3");

                    b.HasIndex(new[] { "ProjId" }, "idx_user_project_proj_id");

                    b.HasIndex(new[] { "UserId" }, "idx_user_project_user_id");

                    b.ToTable("user_project", (string)null);
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.UserTrack", b =>
                {
                    b.Property<int>("userId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("trackId")
                        .HasColumnType("int")
                        .HasColumnName("track_id");

                    b.Property<DateTime?>("EnrolledAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("enrolled_at");

                    b.HasKey("userId", "trackId");

                    b.HasIndex("trackId");

                    b.ToTable("user_track", (string)null);
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.VwCommentThread", b =>
                {
                    b.Property<int>("ComId")
                        .HasColumnType("int")
                        .HasColumnName("com_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int?>("ParentComId")
                        .HasColumnType("int")
                        .HasColumnName("parent_com_id");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("topic");

                    b.Property<int?>("TopicId")
                        .HasColumnType("int")
                        .HasColumnName("topic_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("type");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.ToTable((string)null);

                    b.ToView("vw_comment_threads", (string)null);
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.VwLeaderboard", b =>
                {
                    b.Property<decimal?>("AvgProgress")
                        .HasColumnType("decimal(38, 6)")
                        .HasColumnName("avg_progress");

                    b.Property<int?>("CompletedRoadmaps")
                        .HasColumnType("int")
                        .HasColumnName("completed_roadmaps");

                    b.Property<int?>("Streak")
                        .HasColumnType("int")
                        .HasColumnName("streak");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.ToTable((string)null);

                    b.ToView("vw_leaderboard", (string)null);
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.VwRoadmapDetail", b =>
                {
                    b.Property<decimal?>("AvgRating")
                        .HasColumnType("decimal(38, 6)")
                        .HasColumnName("avg_rating");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<int>("Rid")
                        .HasColumnType("int")
                        .HasColumnName("rid");

                    b.Property<string>("Roadmap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("roadmap");

                    b.Property<int?>("TotalLevels")
                        .HasColumnType("int")
                        .HasColumnName("total_levels");

                    b.Property<int?>("TotalResources")
                        .HasColumnType("int")
                        .HasColumnName("total_resources");

                    b.Property<int?>("TotalReviews")
                        .HasColumnType("int")
                        .HasColumnName("total_reviews");

                    b.Property<int?>("TotalTopics")
                        .HasColumnType("int")
                        .HasColumnName("total_topics");

                    b.Property<string>("Track")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("track");

                    b.ToTable((string)null);

                    b.ToView("vw_roadmap_details", (string)null);
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.VwRoadmapReview", b =>
                {
                    b.Property<string>("Content")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("Rate")
                        .HasColumnType("int")
                        .HasColumnName("rate");

                    b.Property<int>("Rid")
                        .HasColumnType("int")
                        .HasColumnName("rid");

                    b.Property<string>("Roadmap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("roadmap");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.ToTable((string)null);

                    b.ToView("vw_roadmap_reviews", (string)null);
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.VwRoadmapStat", b =>
                {
                    b.Property<decimal?>("AvgRating")
                        .HasColumnType("decimal(38, 6)")
                        .HasColumnName("avg_rating");

                    b.Property<int>("Rid")
                        .HasColumnType("int")
                        .HasColumnName("rid");

                    b.Property<string>("Roadmap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("roadmap");

                    b.Property<int?>("TotalCompletions")
                        .HasColumnType("int")
                        .HasColumnName("total_completions");

                    b.Property<int?>("TotalEnrollments")
                        .HasColumnType("int")
                        .HasColumnName("total_enrollments");

                    b.Property<string>("Track")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("track");

                    b.ToTable((string)null);

                    b.ToView("vw_roadmap_stats", (string)null);
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.VwTopicResource", b =>
                {
                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("level");

                    b.Property<int>("Lid")
                        .HasColumnType("int")
                        .HasColumnName("lid");

                    b.Property<bool?>("Paid")
                        .HasColumnType("bit")
                        .HasColumnName("paid");

                    b.Property<int>("ResId")
                        .HasColumnType("int")
                        .HasColumnName("res_id");

                    b.Property<string>("ResUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("res_url");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("resource");

                    b.Property<int>("ResourceOrder")
                        .HasColumnType("int")
                        .HasColumnName("resource_order");

                    b.Property<int>("Rid")
                        .HasColumnType("int")
                        .HasColumnName("rid");

                    b.Property<string>("Roadmap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("roadmap");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("topic");

                    b.Property<int>("TopicId")
                        .HasColumnType("int")
                        .HasColumnName("topic_id");

                    b.Property<int>("TopicOrder")
                        .HasColumnType("int")
                        .HasColumnName("topic_order");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("type");

                    b.ToTable((string)null);

                    b.ToView("vw_topic_resources", (string)null);
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.VwUserBookmark", b =>
                {
                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("level");

                    b.Property<bool?>("Paid")
                        .HasColumnType("bit")
                        .HasColumnName("paid");

                    b.Property<int>("ResId")
                        .HasColumnType("int")
                        .HasColumnName("res_id");

                    b.Property<string>("ResUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("res_url");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("resource");

                    b.Property<string>("Roadmap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("roadmap");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("topic");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.ToTable((string)null);

                    b.ToView("vw_user_bookmarks", (string)null);
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.VwUserCertificate", b =>
                {
                    b.Property<string>("CertUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("cert_url");

                    b.Property<DateTime?>("IssuedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("issued_at");

                    b.Property<string>("Roadmap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("roadmap");

                    b.Property<string>("Track")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("track");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.ToTable((string)null);

                    b.ToView("vw_user_certificate", (string)null);
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.VwUserDashboard", b =>
                {
                    b.Property<decimal>("CompPerc")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("comp_perc");

                    b.Property<DateTime?>("LastActDate")
                        .HasColumnType("datetime")
                        .HasColumnName("last_act_date");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("level");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("plan");

                    b.Property<string>("Roadmap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("roadmap");

                    b.Property<int?>("Streak")
                        .HasColumnType("int")
                        .HasColumnName("streak");

                    b.Property<string>("Track")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("track");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.ToTable((string)null);

                    b.ToView("vw_user_dashboard", (string)null);
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.VwUserProgress", b =>
                {
                    b.Property<decimal>("CompPerc")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("comp_perc");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("level");

                    b.Property<int>("Lid")
                        .HasColumnType("int")
                        .HasColumnName("lid");

                    b.Property<string>("ProjectStatus")
                        .IsRequired()
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("project_status");

                    b.Property<int>("Rid")
                        .HasColumnType("int")
                        .HasColumnName("rid");

                    b.Property<string>("Roadmap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("roadmap");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.ToTable((string)null);

                    b.ToView("vw_user_progress", (string)null);
                });

            modelBuilder.Entity("UserResource", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("ResId")
                        .HasColumnType("int")
                        .HasColumnName("res_id");

                    b.HasKey("UserId", "ResId")
                        .HasName("PK__user_res__7BB73C5F3DCE2088");

                    b.HasIndex(new[] { "ResId" }, "idx_user_resource_res_id");

                    b.HasIndex(new[] { "UserId" }, "idx_user_resource_user_id");

                    b.ToTable("user_resource", (string)null);
                });

            modelBuilder.Entity("Bookmark", b =>
                {
                    b.HasOne("MindMapManager.Core.Entities.Resource", null)
                        .WithMany()
                        .HasForeignKey("ResId")
                        .IsRequired()
                        .HasConstraintName("res_bookmark_fk");

                    b.HasOne("MindMapManager.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("user_bookmark_fk");
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.ApplicationUser", b =>
                {
                    b.HasOne("MindMapManager.Core.Entities.Plan", "PidNavigation")
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("Pid")
                        .HasConstraintName("user_plan_fk");

                    b.Navigation("PidNavigation");
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.Certificate", b =>
                {
                    b.HasOne("MindMapManager.Core.Entities.Roadmap", "RidNavigation")
                        .WithMany("Certificates")
                        .HasForeignKey("Rid")
                        .HasConstraintName("certificate_roadmap_fk");

                    b.HasOne("MindMapManager.Core.Entities.ApplicationUser", "User")
                        .WithMany("Certificates")
                        .HasForeignKey("UserId")
                        .HasConstraintName("user_certificate_fk");

                    b.Navigation("RidNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.Comment", b =>
                {
                    b.HasOne("MindMapManager.Core.Entities.Comment", "ParentCom")
                        .WithMany("InverseParentCom")
                        .HasForeignKey("ParentComId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("reply_comment_fk");

                    b.HasOne("MindMapManager.Core.Entities.Topic", "Topic")
                        .WithMany("Comments")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("comment_topic_fk");

                    b.Navigation("ParentCom");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.CompletedTopic", b =>
                {
                    b.HasOne("MindMapManager.Core.Entities.Topic", "Topic")
                        .WithMany("CompletedTopics")
                        .HasForeignKey("topicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("completed_user_topic_fk");

                    b.HasOne("MindMapManager.Core.Entities.ApplicationUser", "User")
                        .WithMany("CompletedTopics")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("completed_user_user_fk");

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.Level", b =>
                {
                    b.HasOne("MindMapManager.Core.Entities.Roadmap", "RidNavigation")
                        .WithMany("Levels")
                        .HasForeignKey("Rid")
                        .HasConstraintName("roadmap_level_fk");

                    b.Navigation("RidNavigation");
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.Notification", b =>
                {
                    b.HasOne("MindMapManager.Core.Entities.ApplicationUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .HasConstraintName("user_notification_fk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.Progress", b =>
                {
                    b.HasOne("MindMapManager.Core.Entities.Level", "LidNavigation")
                        .WithMany("Progresses")
                        .HasForeignKey("Lid")
                        .HasConstraintName("progress_level_fk");

                    b.HasOne("MindMapManager.Core.Entities.ApplicationUser", "User")
                        .WithMany("Progresses")
                        .HasForeignKey("UserId")
                        .HasConstraintName("user_progress_fk");

                    b.Navigation("LidNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.Project", b =>
                {
                    b.HasOne("MindMapManager.Core.Entities.Level", "LidNavigation")
                        .WithMany("Projects")
                        .HasForeignKey("Lid")
                        .HasConstraintName("project_level_fk");

                    b.Navigation("LidNavigation");
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.Resource", b =>
                {
                    b.HasOne("MindMapManager.Core.Entities.Topic", "Topic")
                        .WithMany("Resources")
                        .HasForeignKey("TopicId")
                        .HasConstraintName("resource_topic_fk");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.Review", b =>
                {
                    b.HasOne("MindMapManager.Core.Entities.Roadmap", "RidNavigation")
                        .WithMany("Reviews")
                        .HasForeignKey("Rid")
                        .HasConstraintName("roadmap_review_fk");

                    b.HasOne("MindMapManager.Core.Entities.ApplicationUser", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .HasConstraintName("user_review_fk");

                    b.Navigation("RidNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.Roadmap", b =>
                {
                    b.HasOne("MindMapManager.Core.Entities.Track", "Track")
                        .WithMany("Roadmaps")
                        .HasForeignKey("TrackId")
                        .HasConstraintName("track_roadmap_fk");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.Topic", b =>
                {
                    b.HasOne("MindMapManager.Core.Entities.Level", "LidNavigation")
                        .WithMany("Topics")
                        .HasForeignKey("Lid")
                        .HasConstraintName("level_topic_fk");

                    b.Navigation("LidNavigation");
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.UserComment", b =>
                {
                    b.HasOne("MindMapManager.Core.Entities.Comment", "Com")
                        .WithOne("UserComment")
                        .HasForeignKey("MindMapManager.Core.Entities.UserComment", "ComId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("user_comment_com_fk");

                    b.HasOne("MindMapManager.Core.Entities.ApplicationUser", "User")
                        .WithMany("UserComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("user_comment_user_fk");

                    b.Navigation("Com");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.UserProject", b =>
                {
                    b.HasOne("MindMapManager.Core.Entities.Project", "Proj")
                        .WithMany("UserProjects")
                        .HasForeignKey("ProjId")
                        .IsRequired()
                        .HasConstraintName("FK__user_proj__proj___1CBC4616");

                    b.HasOne("MindMapManager.Core.Entities.ApplicationUser", "User")
                        .WithMany("UserProjects")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__user_proj__user___1BC821DD");

                    b.Navigation("Proj");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.UserTrack", b =>
                {
                    b.HasOne("MindMapManager.Core.Entities.Track", "Track")
                        .WithMany("UserTracks")
                        .HasForeignKey("trackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_track_track_fk");

                    b.HasOne("MindMapManager.Core.Entities.ApplicationUser", "User")
                        .WithMany("UserTracks")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_track_user_fk");

                    b.Navigation("Track");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserResource", b =>
                {
                    b.HasOne("MindMapManager.Core.Entities.Resource", null)
                        .WithMany()
                        .HasForeignKey("ResId")
                        .IsRequired()
                        .HasConstraintName("FK__user_reso__res_i__18EBB532");

                    b.HasOne("MindMapManager.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__user_reso__user___17F790F9");
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("CompletedTopics");

                    b.Navigation("Notifications");

                    b.Navigation("Progresses");

                    b.Navigation("Reviews");

                    b.Navigation("UserComments");

                    b.Navigation("UserProjects");

                    b.Navigation("UserTracks");
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.Comment", b =>
                {
                    b.Navigation("InverseParentCom");

                    b.Navigation("UserComment");
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.Level", b =>
                {
                    b.Navigation("Progresses");

                    b.Navigation("Projects");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.Plan", b =>
                {
                    b.Navigation("ApplicationUsers");
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.Project", b =>
                {
                    b.Navigation("UserProjects");
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.Roadmap", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("Levels");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.Topic", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("CompletedTopics");

                    b.Navigation("Resources");
                });

            modelBuilder.Entity("MindMapManager.Core.Entities.Track", b =>
                {
                    b.Navigation("Roadmaps");

                    b.Navigation("UserTracks");
                });
#pragma warning restore 612, 618
        }
    }
}
